### ISSUE TITLE
Type errors caused by semver on Deno v1.11.0

### ISSUE THREAD

**Issue by umbopepato** [nestdotland/hatcher#40]
## 🐛 Bug Report

`semver@1.0.0` - used by Hatcher - causes some type errors on the latest Deno version (v1.11.0).

## To Reproduce

1. Update Deno to v1.11.0
    ```
    $ deno upgrade --version 1.11.0
    ````
2. Run any module which imports from Hatcher

## Expected behavior

No type errors are thrown.

## Actual Behavior

The following errors are thrown:

![image](https://user-images.githubusercontent.com/18363145/121362813-af378380-c936-11eb-8093-4774507f0048.png)

## Environment

- Eggs version: -
- Deno version: 1.11.0
- Operating system and version: macOS Big Sur 11.3.1 (20E241)

## Additional context

#39 should fix this (upgrades `semver` to the latest version) 🙂

**Comment by maximousblk** [comment]
was this fixed by #39?

**Comment by SteelAlloy** [comment]
Yes, I'm reworking the code to support intellisense, next version will be released in a few days
